### ISSUE TITLE
python3 Dockerfile fails after build, when trying to run 

### ISSUE THREAD

**Issue by spyrostz** [gridsingularity/d3a#478]
The python3 Dockerfile installation succeeds without issues, but fails when one tries to run it with the following message: 

Spyross-MacBook-Pro:d3a spyrostzavikas$ docker run --rm d3a --help
Traceback (most recent call last):
  File "/venv/bin/d3a", line 11, in <module>
    load_entry_point('d3a', 'console_scripts', 'd3a')()
  File "/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/app/src/d3a/d3a_core/cli.py", line 36, in <module>
    from d3a.d3a_core.simulation import run_simulation
  File "/app/src/d3a/d3a_core/simulation.py", line 35, in <module>
    from d3a.d3a_core.area_serializer import are_all_areas_unique
  File "/app/src/d3a/d3a_core/area_serializer.py", line 20, in <module>
    from d3a.models.area import Area # NOQA
  File "/app/src/d3a/models/area/__init__.py", line 38, in <module>
    from d3a.models.area.markets import AreaMarkets
  File "/app/src/d3a/models/area/markets.py", line 21, in <module>
    from d3a.models.market.two_sided_pay_as_bid import TwoSidedPayAsBid
  File "/app/src/d3a/models/market/two_sided_pay_as_bid.py", line 22, in <module>
    from d3a.models.market.one_sided import OneSidedMarket
  File "/app/src/d3a/models/market/one_sided.py", line 29, in <module>
    from d3a.models.market.blockchain_interface import MarketBlockchainInterface
  File "/app/src/d3a/models/market/blockchain_interface.py", line 27, in <module>
    from d3a.models.market.blockchain_utils import create_market_contract, create_new_offer, \
  File "/app/src/d3a/models/market/blockchain_utils.py", line 22, in <module>
    from d3a.blockchain.utils import unlock_account, wait_for_node_synchronization
  File "/app/src/d3a/blockchain/__init__.py", line 23, in <module>
    from solc import compile_source
ModuleNotFoundError: No module named 'solc'
Spyross-MacBook-Pro:d3a spyrostzavikas$ 

The problem is that the installation of the Python solidity client is not taken into account for the python3 Dockerfile (keep in mind that the original py-solc module has a broken API at the time of writing, there is a fork that deals with these issues and we use that in local installation, have a look at https://github.com/ethereum/py-solc/issues/64 for more details). Therefore, py-solc installation needs to be added to the python3 Dockerfile. 

DoD: Add py-solc dependency on the python3 Dockerfile.

**Comment by spyrostz** [comment]
PR opened, should solve the issue:

https://github.com/gridsingularity/d3a/pull/479

**Comment by spyrostz** [comment]
PR merged to master, closing the issue.
